POST https://node-videos-api.onrender.com/videos
Content-Type: application/json

{
  "title": "Video 03",
  "description": "Esse é o vídeo 01",
  "duration": 180
}

###

GET https://node-videos-api.onrender.com/videos


###

PUT https://node-videos-api.onrender.com/videos/570895f4-f18f-4285-8f64-b9c814da243c
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o vídeo 02",
  "duration": 180
}

###

DELETE https://node-videos-api.onrender.com/videos/502b2305-3bfc-4519-ba20-f90dac0e6a5f
Content-Type: application/json
